/**:
  ros__parameters:
    host_ip: 192.168.1.102
    sensor_ip: 192.168.1.200
    data_port: 6699
    info_port: 7788
    difop2_port: 7788
    packet_mtu_size: 1500
    launch_hw: false
    setup_sensor: false
    frame_id: robosense
    diag_span: 1000
    dual_return_distance_threshold: 0.1
    sensor_model: EMX
    return_mode: Strongest
